theme: minima
title: Trying my Hand in Creating a Blog static on GitHub
author: vyderzhka with assistance of GitHub bot
email: TBD to be displayed later
description: > # this means to ignore newlines until "baseurl:"
  To Be Updated in due course--->Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
github_username:  vyderzhka # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
